# Generated by Django 3.1.4 on 2020-12-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=3)),
                ('destination_currency', models.FileField(max_length=3, upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
