# Generated by Django 3.1.4 on 2020-12-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcurrencyrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
