# Generated by Django 3.1.4 on 2020-12-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcurrencyrate', '0002_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='destination_currency',
            field=models.CharField(max_length=3),
        ),
    ]
