# Generated by Django 3.1.4 on 2020-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcurrencyrate', '0005_auto_20201224_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(),
        ),
    ]
